Repository cs-371l/crumbs, pull requests merged in 2022-11, with the labels that each got.

#30 [CS371L-50] Link user to created post
  crumbs/crumbs.xcodeproj/project.pbxproj
  crumbs/crumbs/Fixtures.swift
  crumbs/crumbs/Post.swift
  crumbs/crumbs/PostCardViewController.swift
  crumbs/crumbs/PostCreationViewController.swift
  crumbs/crumbs/User.swift
Labels: ui, firebase

#43 [CS371L-56] Add latitude and longitude to posts
  crumbs/crumbs.xcodeproj/project.pbxproj
  crumbs/crumbs/AppDelegate.swift
  crumbs/crumbs/DeviceLocationService.swift
  crumbs/crumbs/Info.plist
  crumbs/crumbs/Post.swift
  crumbs/crumbs/PostCreationViewController.swift
Labels: backend, firebase

#46 Refactoring directory
  crumbs/crumbs.xcodeproj/project.pbxproj
  crumbs/crumbs/models/Comment.swift
  crumbs/crumbs/models/Post.swift
  crumbs/crumbs/models/User.swift
  crumbs/crumbs/storyboards/Base.lproj/LaunchScreen.storyboard
  crumbs/crumbs/storyboards/Base.lproj/Main.storyboard
  crumbs/crumbs/utils/DeviceLocationService.swift
  crumbs/crumbs/utils/ErrorMessage.swift
  crumbs/crumbs/utils/Geohash.swift
  crumbs/crumbs/utils/extensions/UIButtonExtensions.swift
  crumbs/crumbs/utils/extensions/UIImageExtensions.swift
  crumbs/crumbs/utils/extensions/UIViewControllerExtensions.swift
  crumbs/crumbs/views/HomeTabBarController.swift
  crumbs/crumbs/views/ViewController.swift
  crumbs/crumbs/views/account/DeleteAccountViewController.swift
  crumbs/crumbs/views/account/LoginViewController.swift
  crumbs/crumbs/views/account/SignInListenerViewController.swift
  crumbs/crumbs/views/account/SignOutListenerViewController.swift
  crumbs/crumbs/views/account/SignUpViewController.swift
  crumbs/crumbs/views/comments/AddCommentViewController.swift
  crumbs/crumbs/views/feed/FeedViewController.swift
  crumbs/crumbs/views/posts/PostCardViewController.swift
  crumbs/crumbs/views/posts/PostCreationViewController.swift
  crumbs/crumbs/views/posts/PostViewController.swift
  crumbs/crumbs/views/profile/AboutViewController.swift
  crumbs/crumbs/views/profile/EditProfileViewController.swift
  crumbs/crumbs/views/profile/ProfileViewController.swift
  crumbs/crumbs/views/settings/SettingsViewController.swift
Labels: fix
